version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/openjdk:23.0.2
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install maven -y
      - run: mvn --version
      - run: java --version
